module.exports = {
	igdl: require("../scrape/Download/igdl"),
	ttdl: require("../scrape/Download/ttdl"),
	spotifydl: require("../scrape/Download/spotifydl"),
	ytdl: require("../scrape/Download/ytdl"),
	ccdl: require("../scrape/Download/ccdl"),
	youtubeSearch: require("../scrape/Search/youtubeSearch"),
	wikipediaSearch: require("../scrape/Search/wikipediaSearch"),
	wikiImageSearch: require("../scrape/Search/wikiImageSearch"),
	unsplashSearch: require("../scrape/Search/unsplashSearch"),
	tiktokSearch: require("../scrape/Search/tiktokSearch"),
	spotifySearch: require("../scrape/Search/spotifySearch"),
	soundcloudSearch: require("../scrape/Search/soundcloudSearch"),
	sfileSearch: require("../scrape/Search/sfileSearch"),
	playstoreSearch: require("../scrape/Search/playstoreSearch"),
	pinterestSearch: require("../scrape/Search/pinterestSearch"),
	npmSearch: require("../scrape/Search/npmSearch"),
	librarySearch: require("../scrape/Search/librarySearch"),
	appstoreSearch: require("../scrape/Search/appstoreSearch"),
	quotly: require("../scrape/Maker/quotly"),
	emojimix: require("../scrape/Maker/emojimix"),
	carbonV2: require("../scrape/Maker/carbonV2"),
	carbonV1: require("../scrape/Maker/carbonV1"),
	bratVideo: require("../scrape/Maker/bratVideo"),
	bratImage: require("../scrape/Maker/bratImage"),
};
